#{
#  "name": "vni",
#  "main": ".open-next/worker.js",
#  "compatibility_date": "2025-03-25",
#  "compatibility_flags": [
#    "nodejs_compat"
#  ],
#  "assets": {
#    "directory": ".open-next/assets",
#    "binding": "ASSETS"
#  }
#}


name = "vni"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"

compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# --- ADD YOUR ENV VARS HERE ---
[vars]
DIRECT_URL = "postgresql://neondb_owner:npg_u76GmDqjSZbg@ep-bitter-sunset-aflwiqng-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
DATABASE_URL = "prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza195NkREUk14aUVsUjIzWThMaHZkSGkiLCJhcGlfa2V5IjoiMDFLQU1ZVkpZWEZFM1kwQUtaTjk2UEpDSFYiLCJ0ZW5hbnRfaWQiOiI2OTU5ODFkZWU0OTBhOTdkMTYzMjU0NWJjZmU5NGRmYjEwMmM4ZDU4NTVlNDk3ZjQ2Yzk5MWJkMjQzNzg1N2Y1IiwiaW50ZXJuYWxfc2VjcmV0IjoiNDQzNTc5YzUtZmQ5Yy00Y2M5LTk2MGYtYjAxZTg0MDJmZGVjIn0.k52A24CBuSQ9dx4oMaTNSBeg-TKdaqOsa5RUrCSJOi4"
RESEND_API_KEY = "re_DKCeYj5c_8tG8b3SSBuZR36eeHQ4nggVu"
ADMIN_EMAIL = "office@vitalinutri.com"
SEND_EMAIL = "VitaliNutrition <noreply@resend.dev>"

CLOUDFLARE_ACCOUNT_ID = "ec69dedcb4060c2e6340b6d7721dc561"
CLOUDFLARE_ACCESS_KEY_ID = "28c112c5fba4a4306bef6ec1b018d8f4"
CLOUDFLARE_SECRET_ACCESS_KEY = "d3197bded45aee7429aeb8c3e4721a2530ea5c7b6890b9d79816a28eddf16b75"
CLOUDFLARE_TOKEN = "XFQj4pAQu6MoF8RPiHMn-SXxdJ6PLVBrpLHyh8_e"
CLOUDFLARE_BUCKET = "vitali-nutrition-inc-contents-dev"


JWT_ACCESS_TTL_HOUR = 12
JWT_ALG = "HS256"
JWT_SECRET = "0lC1AXjeEywkq8kOPqkajd6Auhc5DZ"
# public
NEXT_PUBLIC_NODE_ENV = "production"
NEXT_PUBLIC_BASE_API_VERSION = "/api/v1"