name = "vni"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"

compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[r2_buckets]]
binding = "VNI_R2_BUCKET"
bucket_name = "vitali-nutrition-inc-contents-prod"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19vNV8tYWNScVlrYzZGbHNRS3lLaTgiLCJhcGlfa2V5IjoiMDFLQVNGNzNFNDNNMkhEMEFIMlNCWlpGRjYiLCJ0ZW5hbnRfaWQiOiJiZjBkNDI2ZjVjYTEwNTkwMGFhZGFhMTFkYTM5MGJiM2RiMmJlZGJhYjdkNTkyZmM1ODI1NjNmOTNiOWMxNDgzIiwiaW50ZXJuYWxfc2VjcmV0IjoiZGNlMWY1YjUtMTM5OS00NDhkLWIwMWMtZWJlNzNlYmY4ZTliIn0.5W-EK1cZ54P6-Wz1O-S_gjuKp2P8oAD1BO81EbgjOJ8"
DIRECT_URL = "postgresql://neondb_owner:npg_u76GmDqjSZbg@ep-long-mud-afximzrk-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
RESEND_API_KEY = "re_DKCeYj5c_8tG8b3SSBuZR36eeHQ4nggVu"
ADMIN_EMAIL = "office@vitalinutri.com"
SEND_EMAIL = "VitaliNutrition <noreply@resend.dev>"

CLOUDFLARE_ACCOUNT_ID = "ec69dedcb4060c2e6340b6d7721dc561"
CLOUDFLARE_ACCESS_KEY_ID = "28c112c5fba4a4306bef6ec1b018d8f4"
CLOUDFLARE_SECRET_ACCESS_KEY = "d3197bded45aee7429aeb8c3e4721a2530ea5c7b6890b9d79816a28eddf16b75"
CLOUDFLARE_TOKEN = "XFQj4pAQu6MoF8RPiHMn-SXxdJ6PLVBrpLHyh8_e"
CLOUDFLARE_BUCKET = "vitali-nutrition-inc-contents-dev"

JWT_ACCESS_TTL_HOUR = 12
JWT_ALG = "HS256"
JWT_SECRET = "0lC1AXjeEywkq8kOPqkajd6Auhc5DZ"
# public
NEXT_PUBLIC_BASE_API_VERSION = "/api/v1"
